when:
  branch: main
  event: [push, manual]

steps:
  publish:
    image: gradle:jdk17-alpine@sha256:46a9f459ab66d3c357c4a19dc6b45922e9333f3f7064c6734654d5c11622ce6e
    commands:
      - ./gradlew modrinth
    secrets:
      - source: MODRINTH_TOKEN
        target: MODRINTH_TOKEN
 
