when:
  branch: main
  event: [push, manual]

steps:
  publish:
    image: gradle:jdk17-alpine@sha256:776ba728f7af4f89cd5ed534792daf77c95bca310196ddd46c864af4d7120649
    commands:
      - ./gradlew modrinth
    secrets:
      - source: MODRINTH_TOKEN
        target: MODRINTH_TOKEN
 
