api-version: "1.20"
name: SimpleSellWand
version: 1.20.2-SNAPSHOT
main: xyz.galaxyy.simplesellwand.SimpleSellWand
loader: xyz.galaxyy.simplesellwand.PluginLibrariesLoader
description: A simple sell wand plugin
author: Saturn745
dependencies:
  server:
    EconomyShopGUI:
      load: OMIT
      required: false
      join-classpath: true
    EconomyShopGUI-Premium:
      load: OMIT
      required: false
      join-classpath: true
    Vault:
      load: OMIT
      required: false
      join-classpath: true
